"""
app/api/routes/verification.py

GET  /api/v1/sessions/{session_id}/verification  — run or retrieve VerificationReport
"""

from __future__ import annotations

import logging
import os
import uuid

from fastapi import APIRouter, HTTPException

from app.bob.integration import run_verification_agent
from app.db import evidence_store
from app.services import session as session_svc
from app.services.verification import (
    aggregate_evidence,
    build_fallback_report,
    generate_documentation_patches,
)

logger = logging.getLogger(__name__)

router = APIRouter()

_WORKING_COPY_ROOT = os.environ.get("REPODOC_WORKING_COPY", "./working_copy")


@router.get("/{session_id}/verification")
async def get_verification_report(session_id: str) -> dict:
    """
    Aggregate all session evidence, invoke the Verification Agent (degrades
    gracefully if Bob is unavailable), persist the report, and return it
    together with any generated documentation patch paths.

    If a report already exists for this session it is returned immediately
    without re-running the agent.
    """
    s = session_svc.get_session(session_id)
    if s is None:
        raise HTTPException(status_code=404, detail="Session not found")

    # Return cached report if available
    existing = evidence_store.get_latest_verification_report(session_id)
    if existing is not None:
        return _report_response(existing, patch_paths=[])

    # Check that an impact run exists (soft dependency — return 422 if absent)
    impact_run = evidence_store.get_latest_impact_run(session_id)
    if impact_run is None:
        raise HTTPException(
            status_code=422,
            detail="No impact run found for this session. Run ImpactScope first.",
        )

    # Aggregate evidence
    evidence = aggregate_evidence(session_id)

    # Try Verification Agent; fall back to static report
    vr = await run_verification_agent(
        session_id=session_id,
        evidence_summary={
            "change_description": evidence["change_description"] or "",
            "impact_node_ids": evidence["impact_node_ids"],
            "component_statuses": evidence["component_statuses"],
            "per_test": evidence["per_test"],
            "inferred_node_ids": evidence["inferred_node_ids"],
            "env_checks": evidence["env_checks"],
        },
    )

    if vr is not None:
        report_dict = vr.model_dump()
    else:
        logger.info(
            "verification: Bob unavailable — building fallback report for session %s",
            session_id,
        )
        report_dict = build_fallback_report(evidence)

    # Generate documentation patches (if any gaps reported)
    patch_paths: list[str] = []
    if report_dict.get("documentation_gaps"):
        patch_paths = generate_documentation_patches(
            report_dict["documentation_gaps"],
            os.path.abspath(_WORKING_COPY_ROOT),
        )

    # Persist
    report_id = str(uuid.uuid4())
    evidence_store.save_verification_report(
        report_id=report_id,
        session_id=session_id,
        components_verified=report_dict["components_verified"],
        unresolved_risks=report_dict["unresolved_risks"],
        documentation_gaps=report_dict["documentation_gaps"],
        pr_summary=report_dict["pr_summary"],
    )

    stored = evidence_store.get_latest_verification_report(session_id)
    return _report_response(stored, patch_paths=patch_paths)


# ── Helpers ────────────────────────────────────────────────────────────────────


def _report_response(report: dict, patch_paths: list[str]) -> dict:
    return {
        "report_id": report["report_id"],
        "session_id": report["session_id"],
        "components_verified": report["components_verified"],
        "unresolved_risks": report["unresolved_risks"],
        "documentation_gaps": report["documentation_gaps"],
        "pr_summary": report["pr_summary"],
        "patch_paths": patch_paths,
        "disclaimer": (
            "This report was generated by RepoDoc. "
            "Passing tests are NOT proof of complete safety. "
            "Review all unresolved risks before submission."
        ),
    }
