"""
app/services/test_generator.py

Generate pytest stub files for each approved TestScenario.
Uses a template approach — no LLM at this step.

OPEN QUESTION (ARCHITECTURE.md §11 item 2): Whether test code itself is
generated by Bob or a template engine is not specified in the PRD.
This implementation uses a template engine; wire Bob if that decision changes.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_TEST_TEMPLATE = '''\
"""
Auto-generated regression test.
Scenario : {name}
Component: {component_id}
Evidence : {source_evidence}
"""

import pytest


def {func_name}():
    # Expected behaviour: {expected_behavior}
    # TODO: implement assertion based on component under test
    raise NotImplementedError(
        "Generated stub — implement the assertion for: {expected_behavior!r}"
    )
'''


class ApprovalRequiredError(Exception):
    """Raised when test generation is attempted without an approved plan."""


def generate_test_files(
    plan: dict,
    working_copy_root: str,
) -> list[str]:
    """
    Write one pytest stub per scenario into working_copy_root/tests/generated/.

    plan must have status == "approved"; raises ApprovalRequiredError otherwise.
    Returns list of absolute paths to generated files.

    Never overwrites files that live outside working_copy_root.
    """
    if plan.get("status") != "approved":
        raise ApprovalRequiredError(
            f"Cannot generate tests: plan {plan.get('plan_id')} status is"
            f" {plan.get('status')!r}, expected 'approved'."
        )

    generated_dir = Path(working_copy_root) / "tests" / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    for scenario in plan.get("scenarios", []):
        component_id: str = scenario.get("component_id", "unknown")
        safe_component = (
            component_id.replace("::", "_").replace("/", "_").replace(".", "_")
        )
        file_path = generated_dir / f"{safe_component}_test.py"

        func_name: str = scenario.get("proposed_test_function", "")
        if not func_name or not func_name.startswith("test_"):
            func_name = f"test_{safe_component}"

        content = _TEST_TEMPLATE.format(
            name=scenario.get("name", ""),
            component_id=component_id,
            source_evidence=scenario.get("source_evidence", ""),
            func_name=func_name,
            expected_behavior=scenario.get("expected_behavior", ""),
        )

        try:
            file_path.write_text(content, encoding="utf-8")
            written.append(str(file_path))
            logger.info("test_generator: wrote %s", file_path)
        except Exception:
            logger.exception("test_generator: failed to write %s", file_path)

    return written
